### ISSUE TITLE
Does this work in Autohotkey v2?

### ISSUE THREAD

**Issue by e-t-l** [AHK-just-me/WatchFolder#3]
Like the title says - does this work in AHK v2? I found [one AHK forum post](https://www.autohotkey.com/boards/viewtopic.php?t=8384) inquiring about adapting the script to v2, but there are no replies to the thread so it's unclear if the poster's question was ever resolved.

**Comment by AHK-just-me** [comment]
The v2 version has been posted here: https://www.autohotkey.com/boards/viewtopic.php?f=83&t=95659
